# Logo
logo_image_source: /svg/brain.svg

# Index Page
index_banner_text: Brett Commandeur
index_banner_text_secondary: Works in Progress
index_font_awesome_icon_css: fa fa-male

# Header
menu:
  Home: /
  Archives: /archives
  About: /about.html
  Contact: /contact.html

# Post
default_post_title: Untitled
default_post_icon: fa-file-text-o

# Archive Date Format
archive_date_format: MMM YYYY
archive_font_awesome_icon_css: fa-folder-open

# About Widget
about_widget_avatar_url: https://pbs.twimg.com/profile_images/946445578216468481/0yLxU5Cm_400x400.jpg
about_widget_text: "My name is Brett Commandeur and I'm a computing science student with a passion for user experience."


# Comments.
comments:
  # Disqus comments
  disqus_shortname: 

# Google Analytics Tracking ID
google_analytics:

# Social Media Platforms
social_platforms:
  - url: https://twitter.com/bcmdr
    fa_icon: fa-twitter
  - url: https://www.facebook.com/bcmdr
    fa_icon: fa-facebook
  # - url: https://dribbble.com/
  #   fa_icon: fa-dribbble 
  - url: https://github.com/bcmdr
    fa_icon: fa-github
  # - url: https://plus.google.com/
  #   fa_icon: fa-google-plus
  # - url: https://www.behance.net/
  #   fa_icon: fa-behance
  # - url: https://500px.com/
  #   fa_icon: fa-500px
  - url: mailto:bcmdr.co@gmail.com
    fa_icon: fa-envelope
  # - url: /#
  #   fa_icon: fa-rss

# Footer about
footer_about: "© Brett Commandeur | Design by <a class=\"link dim white\" href=\"http://www.codeblocq.com/\">Jonathan Klughertz</a> | Powered by Hexo<br>Brain by Semmel Zenko from the Noun Project</br>"
